export const KNOWLEDGE_CATEGORIES = {
    targeting: {
        label: 'Targeting & Qualification',
        file: 'targeting.md',
        keywords: [
            'qualify',
            'fit',
            'prospect',
            'target',
            'industry',
            'good fit',
            'bad fit',
            'red flag',
            'ideal',
            'segment',
            'who',
        ],
    },
    'sales-process': {
        label: 'Sales Process',
        file: 'sales-process.md',
        keywords: [
            'discovery',
            'call',
            'meeting',
            'approach',
            'demo',
            'stakeholder',
            'question',
            'prepare',
            'prep',
            'sell',
            'close',
            'pipeline',
        ],
    },
    'pricing-models': {
        label: 'Pricing Models',
        file: 'pricing-models.md',
        keywords: [
            'price',
            'pricing',
            'cost',
            'charge',
            'fee',
            'monthly',
            'discount',
            'rebate',
            'commercial',
            'invest',
            'budget',
            'roi',
        ],
    },
    objections: {
        label: 'Objection Handling',
        file: 'objections.md',
        keywords: [
            'objection',
            'pushback',
            'concern',
            'worry',
            'expensive',
            'canva',
            'sharepoint',
            'time',
            'budget',
            'competitor',
            'tried before',
            'won\'t use',
        ],
    },
    'product-knowledge': {
        label: 'Product Knowledge',
        file: 'product-knowledge.md',
        keywords: [
            'feature',
            'template',
            'pageflex',
            'storefront',
            'v8',
            'v9',
            'v10',
            'version',
            'capability',
            'how does',
            'what does',
            'explain',
            'technical',
            'api',
            'sso',
        ],
    },
    'proposals-value': {
        label: 'Proposals & Value',
        file: 'proposals-value.md',
        keywords: [
            'proposal',
            'email',
            'draft',
            'write',
            'value',
            'story',
            'roi calc',
            'business case',
            'save',
            'time saving',
        ],
    },
    implementation: {
        label: 'Implementation',
        file: 'implementation.md',
        keywords: [
            'implement',
            'poc',
            'proof',
            'pilot',
            'onboard',
            'timeline',
            'project',
            'go-live',
            'deploy',
            'milestone',
            'train',
        ],
    },
    'account-growth': {
        label: 'Account Growth',
        file: 'account-growth.md',
        keywords: [
            'grow',
            'expand',
            'upsell',
            'cross-sell',
            'rescue',
            'under-used',
            'adoption',
            'renewal',
            'churn',
            'review',
            'quarterly',
            'vulnerable',
        ],
    },
} as const;

export type KnowledgeCategory =
    keyof typeof KNOWLEDGE_CATEGORIES;
